export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  OPTION_NOT_ALLOWED: "OPTION_NOT_ALLOWED",
  EMPLOYEE_NOT_ALLOCATED: "EMPLOYEE_NOT_ALLOCATED",
  APPROVED_ENTRY_EDIT: "APPROVED_ENTRY_EDIT",
  REJECTION_WITHOUT_REASON: "REJECTION_WITHOUT_REASON",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  LINE_ALREADY_APPROVED: "LINE_ALREADY_APPROVED",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
